variables:
  DOCKER_REV: "243a00f06550e6b9a00fa0f1530d1bb761e8b7cc"
  BINDIST_REF: "master"
  BINDIST_URL: "https://gitlab.haskell.org/ghc/ghc/-/jobs/artifacts/$BINDIST_REF/raw/ghc-$BINDIST_JOB.tar.xz"

.build:
  script:
    - |
      if [ -z "$GHC" ]; then
        echo "Fetching bootstrap GHC via ghcup..."
        export BOOTSTRAP_HASKELL_NONINTERACTIVE=1
        export GHCUP_DIR="$CI_PROJECT_DIR/ghcup"
        export GHCUP_USE_XDG_DIRS=1
        export XDG_DATA_HOME="$GHCUP_DIR/share"
        export XDG_BIN_HOME="$GHCUP_DIR/bin"
        curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
        export GHC="$GHCUP_DIR/bin/ghc"
        export CABAL="$GHCUP_DIR/bin/cabal"
      fi
    - |
       mkdir -p tmp
       cd tmp
       echo "Fetching binary distribution from $BINDIST_URL..."
       # Job names may contain characters that need to be url-encoded.
       curl --get -L "$BINDIST_URL" --data-urlencode "job=$BINDIST_JOB" | tar -xJ
       cd ghc-*
       ./configure --prefix="$CI_PROJECT_DIR/test-ghc" "${CONFIGURE_ARGS[@]}"
       make install
       cd "$CI_PROJECT_DIR"
    - rm -Rf tmp
    - |
       export TEST_GHC="$CI_PROJECT_DIR/test-ghc/bin/ghc"
       export BOOT_GHC="$GHC"
       find .

       echo "Boot GHC:"
       "$BOOT_GHC" --version
       echo ""

       echo "Test GHC:"
       "$TEST_GHC" --version
       echo ""

       ARGS=()
       if [ -n "$NO_LLVM" ]; then
         echo "Skipping LLVM backend tests..."
         ARGS+=("-p" '$2 !~ /llvm/')
       fi

       ./run.sh run "${ARGS[@]}"

x86_64-linux:
  extends: .build
  variables:
    BINDIST_JOB: "x86_64-linux-deb10-validate+debug_info"
    NO_LLVM: 1
  image: "registry.gitlab.haskell.org/ghc/ci-images/x86_64-linux-deb10:$DOCKER_REV"
  tags:
    - x86_64-linux

x86_64-darwin:
  extends: .build
  variables:
    BINDIST_JOB: "x86_64-darwin-validate"
    NO_LLVM: 1
  tags:
    - x86_64-darwin

aarch64-darwin:
  extends: .build
  variables:
    BINDIST_JOB: "aarch64-darwin-validate"
    NO_LLVM: 1
  tags:
    - aarch64-darwin
  
