variables:
  GIT_STRATEGY: clone

  # We run the expression correctness tests significantly more iterations
  # since they cover a much larger phase space.
  # See Note [Tests of test-primops] in app/Main.hs
  EXPR_TESTS: 10000
  OTHER_TESTS: 100

include: template.yml


# The validate pipelines

x86_64-linux:
  extends: .build-x86_64-linux-deb12
  rules:
    - if: '$UPSTREAM_PIPELINE_ID'
      when: never
    - when: always

i386-linux:
  extends: .build-i386-linux-deb10
  rules:
    - if: '$UPSTREAM_PIPELINE_ID'
      when: never
    - when: always

x86_64-darwin:
  extends: .build-x86_64-darwin
  rules:
    - if: '$UPSTREAM_PIPELINE_ID'
      when: never
    - when: always

aarch64-darwin:
  extends: .build-aarch64-darwin
  rules:
    - if: '$UPSTREAM_PIPELINE_ID'
      when: never
    - when: always

aarch64-linux:
  extends: .build-aarch64-linux-deb12
  rules:
    - if: '$UPSTREAM_PIPELINE_ID'
      when: never
    - when: always

update-branch:
  image: "nixos/nix:2.14.1"
  tags:
    - x86_64-linux
  script:
    - git remote -v
    - git reset --hard origin/master
    - git push "https://gitlab-ci-token:$PROJECT_PUSH_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git" +HEAD:upstream-testing -o ci.skip
  rules:
    - if: $CI_COMMIT_BRANCH == "master"


# Upstream triggered

upstream:
  image: nixos/nix:2.14.1
  tags:
    - x86_64-linux
  before_script:
    - echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
    - nix-channel --update
  script:
    - nix shell --extra-experimental-features nix-command -f .gitlab/ -c gen_ci --pipeline-id="$UPSTREAM_PIPELINE_ID" > "generated-config.yml"

  rules:
    - if: '$UPSTREAM_PIPELINE_ID'
      when: always
    - when: never
  artifacts:
    paths:
      - generated-config.yml

test-upstream:
  needs: ["upstream"]
  rules:
    - if: '$UPSTREAM_PIPELINE_ID'
      when: always
    - when: never
  trigger:
    strategy: depend
    include:
      - artifact: generated-config.yml
        job: upstream


