cabal-version:      2.4
name:               test-primops
version:            0.1.0.0
author:             Ben Gamari
maintainer:         ben@smart-cactus.org
license:            BSD-3-Clause
copyright:          (c) 2021 Ben Gamari
synopsis:
  A QuickCheck testsuite for GHC's Cmm pipeline.

executable test-primops
    main-is:          Main.hs
    hs-source-dirs:   src
    other-modules:    Width,
                      Number,
                      Expr,
                      Expr.Parse,
                      Compiler,
                      Interpreter,
                      ToCmm,
                      CallishOp,
                      CCall,
                      MulMayOverflow,
                      RunGhc
    build-depends:    base,
                      QuickCheck,
                      bytestring,
                      containers,
                      directory,
                      filepath,
                      megaparsec,
                      optparse-applicative,
                      parser-combinators,
                      process,
                      tagged,
                      tasty,
                      tasty-quickcheck,
                      temporary,
                      transformers
    build-tool-depends: run-it:run-it
    ghc-options:      -Wall -Wno-unticked-promoted-constructors -threaded
    default-extensions:
        AllowAmbiguousTypes
        DataKinds
        FlexibleContexts
        GADTs
        MultiParamTypeClasses
        RankNTypes
        ScopedTypeVariables
        TypeApplications
        TypeInType
        TypeOperators
        ViewPatterns
    default-language: Haskell2010

