cabal-version:      2.4
name:               test-primops
version:            0.1.0.0
author:             Ben Gamari
maintainer:         ben@smart-cactus.org
license:            BSD-3-Clause
copyright:          (c) 2021 Ben Gamari
synopsis:
  A QuickCheck testsuite for GHC's Cmm pipeline.

flag target-32bit
    description:     Set to True when the compiler-under-test targets a
                     platform with 32-bit word-size.
    default:         False
    manual:          True

common warnings
    ghc-options:      -Wall -Wno-unticked-promoted-constructors

library
    import:           warnings
    hs-source-dirs:   src
    if flag(target-32bit)
        cpp-options:  -DWORD_SIZE_32BIT
    else
        cpp-options:  -DWORD_SIZE_64BIT
    exposed-modules:  Width,
                      Number,
                      Expr,
                      Expr.Parse,
                      Compiler,
                      Interpreter,
                      ToCmm,
                      CallishOp,
                      CCall,
                      MulMayOverflow,
                      RunGhc
    build-depends:    base,
                      QuickCheck,
                      bytestring,
                      containers,
                      directory,
                      filepath,
                      megaparsec,
                      optparse-applicative,
                      parser-combinators,
                      process,
                      tagged,
                      tasty,
                      tasty-quickcheck,
                      temporary,
                      transformers
    build-tool-depends: run-it:run-it
    ghc-options:      -threaded
    default-extensions:
        AllowAmbiguousTypes
        DataKinds
        FlexibleContexts
        GADTs
        MultiParamTypeClasses
        RankNTypes
        ScopedTypeVariables
        TypeApplications
        TypeInType
        TypeOperators
        ViewPatterns
    default-language: Haskell2010

executable test-primops
    import:           warnings
    main-is:          Main.hs
    hs-source-dirs:   app
    build-depends:    base,
                      QuickCheck,
                      directory,
                      filepath,
                      optparse-applicative,
                      tasty,
                      tasty-quickcheck,
                      test-primops
    build-tool-depends: run-it:run-it
    ghc-options:      -threaded
    default-language: Haskell2010

