cabal-version:      3.0
name:               run-it
version:            0.1.0.0
author:             Ben Gamari
maintainer:         ben@smart-cactus.org
license:            BSD-3-Clause
copyright:          (c) 2021 Ben Gamari
synopsis:
  A small shim for dynamically loading and evaluating code from shared objects.

executable run-it
    main-is:          Run.hs
    cmm-sources:      Trampoline.cmm
    build-depends:    base ^>=4.14.3.0,
                      unix,
                      mmap
    ghc-options:      -Wall -Wno-unticked-promoted-constructors
    default-language: Haskell2010

